# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 在当前环境中拉取你仓库然后进入到目录，下面的步骤在仓库的根目录中进行
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.TOKEN }}
          TARGET_REPO: huixiongyu/vuepress-publish
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: yarn && yarn build
          BUILD_DIR: docs/.vuepress/dist/
          CNAME: ${{ secrets.CNAME }}
          
  build-to-OSS:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: |
          yarn add -D vuepress
          yarn install
          yarn build
          cd docs/.vuepress/dist
          echo '${{ secrets.OSS_CNAME }}' > CNAME
            
    - name: Upload to oss
      id: upload_to_oss
      uses: tvrcgo/upload-to-oss@master
      with:
        key-id: ${{ secrets.OSS_KEY }}
        key-secret: ${{ secrets.OSS_SECRET }}
        region: oss-cn-guangzhou
        bucket: huixiong-blog
        assets: ｜
          ./**:/public/
          
